### ISSUE TITLE
fails to build with ghc-9.10.1

### ISSUE THREAD

**Issue by juhp** [prikhi/hledger-stockquotes#16]
For Stackage Nightly

```
       Building library for hledger-stockquotes-0.1.3.1...
       [1 of 3] Compiling Paths_hledger_stockquotes
       [2 of 3] Compiling Web.AlphaVantage
       [3 of 3] Compiling Hledger.StockQuotes
       /home/curators/work/unpack-dir/unpacked/hledger-stockquotes-0.1.3.1-4adc3380b6f1424aa79c5a881edc36f9e7ec39a431f22d8db98190811
ba9aacb/src/Hledger/StockQuotes.hs:81:25: error: [GHC-88464]
           Variable not in scope: jcommodities :: Journal -> M.Map T.Text a1
          |
       81 |                 M.keys (jcommodities journal)
          |                         ^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/hledger-stockquotes-0.1.3.1-4adc3380b6f1424aa79c5a881edc36f9e7ec39a431f22d8db98190811
ba9aacb/src/Hledger/StockQuotes.hs:82:32: error: [GHC-88464]
           Variable not in scope: 
             jinferredcommodities :: Journal -> M.Map T.Text a0
           Suggested fix:
             Perhaps use one of these:
               record field of Journal ‘jdeclaredcommodities’ (imported from Hledger),
               record field of Journal ‘jinferredcommoditystyles’ (imported from Hledger)
          |
       82 |                     <> M.keys (jinferredcommodities journal)
          |                                ^^^^^^^^^^^^^^^^^^^^
```

**Comment by prikhi** [comment]
Thanks, fixed in v0.1.3.2
